// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.DASHusoCPUTotal", b =>
                {
                    b.Property<DateTimeOffset>("timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("jobname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lpar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipochart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("usoCpuPorcentaje")
                        .HasColumnType("float");

                    b.Property<string>("workload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("timestamp");

                    b.ToTable("DASHusoCPUTotal");
                });
#pragma warning restore 612, 618
        }
    }
}
